// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/art/art.proto

package net_audiostrike_art

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArtRequest struct {
	ArtistId             string   `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	ArtistTrackId        string   `protobuf:"bytes,2,opt,name=artist_track_id,json=artistTrackId,proto3" json:"artist_track_id,omitempty"`
	Since                uint64   `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtRequest) Reset()         { *m = ArtRequest{} }
func (m *ArtRequest) String() string { return proto.CompactTextString(m) }
func (*ArtRequest) ProtoMessage()    {}
func (*ArtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{0}
}

func (m *ArtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtRequest.Unmarshal(m, b)
}
func (m *ArtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtRequest.Marshal(b, m, deterministic)
}
func (m *ArtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtRequest.Merge(m, src)
}
func (m *ArtRequest) XXX_Size() int {
	return xxx_messageInfo_ArtRequest.Size(m)
}
func (m *ArtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArtRequest proto.InternalMessageInfo

func (m *ArtRequest) GetArtistId() string {
	if m != nil {
		return m.ArtistId
	}
	return ""
}

func (m *ArtRequest) GetArtistTrackId() string {
	if m != nil {
		return m.ArtistTrackId
	}
	return ""
}

func (m *ArtRequest) GetSince() uint64 {
	if m != nil {
		return m.Since
	}
	return 0
}

type Artist struct {
	ArtistId             string   `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pubkey               string   `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Artist) Reset()         { *m = Artist{} }
func (m *Artist) String() string { return proto.CompactTextString(m) }
func (*Artist) ProtoMessage()    {}
func (*Artist) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{1}
}

func (m *Artist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artist.Unmarshal(m, b)
}
func (m *Artist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artist.Marshal(b, m, deterministic)
}
func (m *Artist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artist.Merge(m, src)
}
func (m *Artist) XXX_Size() int {
	return xxx_messageInfo_Artist.Size(m)
}
func (m *Artist) XXX_DiscardUnknown() {
	xxx_messageInfo_Artist.DiscardUnknown(m)
}

var xxx_messageInfo_Artist proto.InternalMessageInfo

func (m *Artist) GetArtistId() string {
	if m != nil {
		return m.ArtistId
	}
	return ""
}

func (m *Artist) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Artist) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

type ArtistPublication struct {
	Artist                 *Artist  `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Signature              string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SerializedArtResources []byte   `protobuf:"bytes,3,opt,name=serialized_art_resources,json=serializedArtResources,proto3" json:"serialized_art_resources,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ArtistPublication) Reset()         { *m = ArtistPublication{} }
func (m *ArtistPublication) String() string { return proto.CompactTextString(m) }
func (*ArtistPublication) ProtoMessage()    {}
func (*ArtistPublication) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{2}
}

func (m *ArtistPublication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtistPublication.Unmarshal(m, b)
}
func (m *ArtistPublication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtistPublication.Marshal(b, m, deterministic)
}
func (m *ArtistPublication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtistPublication.Merge(m, src)
}
func (m *ArtistPublication) XXX_Size() int {
	return xxx_messageInfo_ArtistPublication.Size(m)
}
func (m *ArtistPublication) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtistPublication.DiscardUnknown(m)
}

var xxx_messageInfo_ArtistPublication proto.InternalMessageInfo

func (m *ArtistPublication) GetArtist() *Artist {
	if m != nil {
		return m.Artist
	}
	return nil
}

func (m *ArtistPublication) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ArtistPublication) GetSerializedArtResources() []byte {
	if m != nil {
		return m.SerializedArtResources
	}
	return nil
}

type ArtResources struct {
	Artists              []*Artist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Albums               []*Album  `protobuf:"bytes,2,rep,name=albums,proto3" json:"albums,omitempty"`
	Tracks               []*Track  `protobuf:"bytes,3,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Peers                []*Peer   `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ArtResources) Reset()         { *m = ArtResources{} }
func (m *ArtResources) String() string { return proto.CompactTextString(m) }
func (*ArtResources) ProtoMessage()    {}
func (*ArtResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{3}
}

func (m *ArtResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtResources.Unmarshal(m, b)
}
func (m *ArtResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtResources.Marshal(b, m, deterministic)
}
func (m *ArtResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtResources.Merge(m, src)
}
func (m *ArtResources) XXX_Size() int {
	return xxx_messageInfo_ArtResources.Size(m)
}
func (m *ArtResources) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtResources.DiscardUnknown(m)
}

var xxx_messageInfo_ArtResources proto.InternalMessageInfo

func (m *ArtResources) GetArtists() []*Artist {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *ArtResources) GetAlbums() []*Album {
	if m != nil {
		return m.Albums
	}
	return nil
}

func (m *ArtResources) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

func (m *ArtResources) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Album struct {
	ArtistId             string   `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	ArtistAlbumId        string   `protobuf:"bytes,2,opt,name=artist_album_id,json=artistAlbumId,proto3" json:"artist_album_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ArtistTrackId        []string `protobuf:"bytes,4,rep,name=artist_track_id,json=artistTrackId,proto3" json:"artist_track_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Album) Reset()         { *m = Album{} }
func (m *Album) String() string { return proto.CompactTextString(m) }
func (*Album) ProtoMessage()    {}
func (*Album) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{4}
}

func (m *Album) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Album.Unmarshal(m, b)
}
func (m *Album) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Album.Marshal(b, m, deterministic)
}
func (m *Album) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Album.Merge(m, src)
}
func (m *Album) XXX_Size() int {
	return xxx_messageInfo_Album.Size(m)
}
func (m *Album) XXX_DiscardUnknown() {
	xxx_messageInfo_Album.DiscardUnknown(m)
}

var xxx_messageInfo_Album proto.InternalMessageInfo

func (m *Album) GetArtistId() string {
	if m != nil {
		return m.ArtistId
	}
	return ""
}

func (m *Album) GetArtistAlbumId() string {
	if m != nil {
		return m.ArtistAlbumId
	}
	return ""
}

func (m *Album) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Album) GetArtistTrackId() []string {
	if m != nil {
		return m.ArtistTrackId
	}
	return nil
}

type Track struct {
	ArtistId             string   `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	ArtistAlbumId        string   `protobuf:"bytes,2,opt,name=artist_album_id,json=artistAlbumId,proto3" json:"artist_album_id,omitempty"`
	ArtistTrackId        string   `protobuf:"bytes,3,opt,name=artist_track_id,json=artistTrackId,proto3" json:"artist_track_id,omitempty"`
	AlbumTrackNumber     uint32   `protobuf:"varint,4,opt,name=album_track_number,json=albumTrackNumber,proto3" json:"album_track_number,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{5}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetArtistId() string {
	if m != nil {
		return m.ArtistId
	}
	return ""
}

func (m *Track) GetArtistAlbumId() string {
	if m != nil {
		return m.ArtistAlbumId
	}
	return ""
}

func (m *Track) GetArtistTrackId() string {
	if m != nil {
		return m.ArtistTrackId
	}
	return ""
}

func (m *Track) GetAlbumTrackNumber() uint32 {
	if m != nil {
		return m.AlbumTrackNumber
	}
	return 0
}

func (m *Track) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Peer struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fef21c75be787, []int{6}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *Peer) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Peer) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*ArtRequest)(nil), "net.audiostrike.art.ArtRequest")
	proto.RegisterType((*Artist)(nil), "net.audiostrike.art.Artist")
	proto.RegisterType((*ArtistPublication)(nil), "net.audiostrike.art.ArtistPublication")
	proto.RegisterType((*ArtResources)(nil), "net.audiostrike.art.ArtResources")
	proto.RegisterType((*Album)(nil), "net.audiostrike.art.Album")
	proto.RegisterType((*Track)(nil), "net.audiostrike.art.Track")
	proto.RegisterType((*Peer)(nil), "net.audiostrike.art.Peer")
}

func init() { proto.RegisterFile("pkg/art/art.proto", fileDescriptor_a83fef21c75be787) }

var fileDescriptor_a83fef21c75be787 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0xb7, 0xb1, 0xfd, 0x93, 0xa1, 0x11, 0x74, 0x41, 0x95, 0x69, 0x91, 0x88, 0x7c, 0xa8,
	0x72, 0x40, 0xae, 0x94, 0x0a, 0x89, 0x6b, 0x2e, 0xa0, 0x5e, 0x50, 0x59, 0x38, 0x71, 0x89, 0xd6,
	0xf1, 0x28, 0xac, 0x92, 0xd8, 0x66, 0x77, 0x7c, 0x80, 0x47, 0xe0, 0x29, 0x78, 0x0c, 0x9e, 0x86,
	0x67, 0x41, 0x3b, 0xeb, 0x28, 0x16, 0xb8, 0x85, 0x03, 0x87, 0x48, 0xb3, 0x33, 0xdf, 0x7c, 0xf3,
	0xad, 0xf7, 0x9b, 0xc0, 0x49, 0xb3, 0x59, 0x5f, 0x6a, 0x4b, 0xfe, 0x97, 0x37, 0xb6, 0xa6, 0x5a,
	0x3e, 0xaa, 0x90, 0x72, 0xdd, 0x96, 0xa6, 0x76, 0x64, 0xcd, 0x06, 0x73, 0x6d, 0x29, 0x5b, 0x03,
	0x2c, 0x2c, 0x29, 0xfc, 0xd4, 0xa2, 0x23, 0x79, 0x0e, 0x63, 0x6d, 0xc9, 0x38, 0x5a, 0x9a, 0x32,
	0x15, 0x53, 0x31, 0x1b, 0xab, 0x7b, 0x21, 0x71, 0x5d, 0xca, 0x0b, 0x78, 0xd0, 0x15, 0xc9, 0xea,
	0xd5, 0xc6, 0x43, 0x8e, 0x18, 0x32, 0x09, 0xe9, 0xf7, 0x3e, 0x7b, 0x5d, 0xca, 0xc7, 0x10, 0x3b,
	0x53, 0xad, 0x30, 0x1d, 0x4d, 0xc5, 0x2c, 0x52, 0xe1, 0x90, 0xbd, 0x85, 0x64, 0xc1, 0xb0, 0xbb,
	0x87, 0x48, 0x88, 0x2a, 0xbd, 0xc3, 0x8e, 0x99, 0x63, 0x79, 0x0a, 0x49, 0xd3, 0x16, 0x1b, 0xfc,
	0xcc, 0x8c, 0x63, 0xd5, 0x9d, 0xb2, 0x6f, 0x02, 0x4e, 0x02, 0xe7, 0x4d, 0x5b, 0x6c, 0xcd, 0x4a,
	0x93, 0xa9, 0x2b, 0x79, 0x05, 0x49, 0x60, 0x63, 0xee, 0xfb, 0xf3, 0xf3, 0x7c, 0xe0, 0xde, 0x79,
	0xe8, 0x53, 0x1d, 0x54, 0x3e, 0x85, 0xb1, 0x33, 0xeb, 0x4a, 0x53, 0x6b, 0xf7, 0xb3, 0x0f, 0x09,
	0xf9, 0x12, 0x52, 0x87, 0xd6, 0xe8, 0xad, 0xf9, 0x82, 0xe5, 0x52, 0x5b, 0x5a, 0x5a, 0x74, 0x75,
	0x6b, 0x57, 0xe8, 0x58, 0xd2, 0xb1, 0x3a, 0x3d, 0xd4, 0xf9, 0x73, 0x76, 0xd5, 0xec, 0x87, 0x80,
	0xe3, 0x7e, 0x42, 0xbe, 0x80, 0xff, 0xc3, 0x48, 0x97, 0x8a, 0xe9, 0xe8, 0x4f, 0xf2, 0xf6, 0x58,
	0x39, 0x87, 0x44, 0x6f, 0x8b, 0x76, 0xe7, 0xd2, 0x23, 0xee, 0x3a, 0x1b, 0xee, 0xf2, 0x10, 0xd5,
	0x21, 0x7d, 0x0f, 0x3f, 0x94, 0xd7, 0x78, 0x7b, 0x0f, 0xbf, 0x9a, 0xea, 0x90, 0xf2, 0x12, 0xe2,
	0x06, 0xd1, 0xba, 0x34, 0xe2, 0x96, 0x27, 0x83, 0x2d, 0x37, 0x88, 0x56, 0x05, 0x5c, 0xf6, 0x55,
	0x40, 0xcc, 0x63, 0xff, 0xd6, 0x3b, 0x2c, 0xee, 0x37, 0xef, 0x30, 0x45, 0xf0, 0x0e, 0x19, 0xda,
	0x62, 0xf7, 0xd2, 0xe1, 0x30, 0xe4, 0x3c, 0xaf, 0xef, 0x57, 0xe7, 0x65, 0xdf, 0x05, 0xc4, 0x1c,
	0xff, 0x1b, 0x31, 0x03, 0x63, 0x47, 0x43, 0x86, 0x7f, 0x0e, 0x32, 0x10, 0x05, 0x58, 0xd5, 0xee,
	0x0a, 0xb4, 0x69, 0x34, 0x15, 0xb3, 0x89, 0x7a, 0xc8, 0x15, 0x46, 0xbe, 0xe1, 0xfc, 0xe1, 0x8a,
	0x71, 0xef, 0x8a, 0xd9, 0x2b, 0x88, 0xfc, 0x67, 0xed, 0x79, 0x5d, 0xf4, 0xbd, 0xee, 0xf7, 0xe2,
	0x63, 0xed, 0x68, 0xbf, 0x17, 0x3e, 0xf6, 0xb9, 0xa6, 0xb6, 0xc4, 0xa2, 0x26, 0x8a, 0xe3, 0xf9,
	0x07, 0x18, 0x2d, 0x2c, 0xc9, 0x77, 0x90, 0xbc, 0x46, 0xf2, 0xd1, 0xb3, 0xdb, 0xfc, 0xd5, 0xed,
	0xfc, 0xd9, 0xc5, 0x1d, 0x06, 0xec, 0xed, 0x55, 0xf6, 0x5f, 0x91, 0xf0, 0xff, 0xc8, 0xd5, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0x3d, 0x15, 0xd6, 0x5c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArtClient is the client API for Art service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArtClient interface {
	GetArt(ctx context.Context, in *ArtRequest, opts ...grpc.CallOption) (*ArtistPublication, error)
}

type artClient struct {
	cc *grpc.ClientConn
}

func NewArtClient(cc *grpc.ClientConn) ArtClient {
	return &artClient{cc}
}

func (c *artClient) GetArt(ctx context.Context, in *ArtRequest, opts ...grpc.CallOption) (*ArtistPublication, error) {
	out := new(ArtistPublication)
	err := c.cc.Invoke(ctx, "/net.audiostrike.art.Art/GetArt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtServer is the server API for Art service.
type ArtServer interface {
	GetArt(context.Context, *ArtRequest) (*ArtistPublication, error)
}

// UnimplementedArtServer can be embedded to have forward compatible implementations.
type UnimplementedArtServer struct {
}

func (*UnimplementedArtServer) GetArt(ctx context.Context, req *ArtRequest) (*ArtistPublication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArt not implemented")
}

func RegisterArtServer(s *grpc.Server, srv ArtServer) {
	s.RegisterService(&_Art_serviceDesc, srv)
}

func _Art_GetArt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtServer).GetArt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.audiostrike.art.Art/GetArt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtServer).GetArt(ctx, req.(*ArtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Art_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.audiostrike.art.Art",
	HandlerType: (*ArtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArt",
			Handler:    _Art_GetArt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/art/art.proto",
}
