// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/audiostrike/music/internal"
)

// Injectors from wire_db.go:

func injectArtServer(db *audiostrike.AustkDb) audiostrike.ArtServer {
	dbServer := audiostrike.NewDbServer(db)
	artServer := useDbServer(dbServer)
	return artServer
}

// wire_db.go:

func useDbServer(dbServer *audiostrike.DbServer) audiostrike.ArtServer {
	return dbServer
}
